# Generated by Django 4.2.4 on 2023-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0003_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('flaticon-promotion', 'flaticon-promotion'), ('flaticon-web-programming', 'flaticon-web-programming'), ('flaticon-creativity', 'flaticon-creativity')], default='flaticon-promotion', max_length=50),
            preserve_default=False,
        ),
    ]
