# Generated by Django 4.2.4 on 2023-08-23 10:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 300], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 300], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 300], upload_to='project'),
        ),
    ]
