# Generated by Django 4.2.4 on 2023-08-23 11:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0008_alter_project_image_alter_project_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 300], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 300], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 300], upload_to='project'),
        ),
    ]
