# Generated by Django 4.1.7 on 2023-09-26 21:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0009_alter_project_image_alter_project_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/design.png', force_format=None, keep_meta=True, quality=100, scale=None, size=[638, 411], upload_to='service'),
            preserve_default=False,
        ),
    ]
