# Generated by Django 4.1.7 on 2023-09-26 21:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0010_remove_service_image_service_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[380, 350], upload_to='service'),
        ),
    ]
