# Generated by Django 4.1.7 on 2023-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0011_alter_service_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image3',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='media/project/a.jpeg', upload_to='service'),
            preserve_default=False,
        ),
    ]
