# Generated by Django 4.1.7 on 2023-10-01 11:38

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0017_service_answer1_service_answer2_service_answer3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1600, 2000], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1600, 2000], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1600, 2000], upload_to='project'),
        ),
    ]
