# Generated by Django 4.2.16 on 2024-12-04 03:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('foli', '0018_alter_project_date_alter_project_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/c.jpg', force_format=None, keep_meta=True, null=True, quality=100, scale=1.0, size=[2000, 1600], upload_to='project'),
        ),
        migrations.AddField(
            model_name='project',
            name='image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/c.jpg', force_format=None, keep_meta=True, null=True, quality=100, scale=1.0, size=[2000, 1600], upload_to='project'),
        ),
        migrations.AddField(
            model_name='project',
            name='image6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/c.jpg', force_format=None, keep_meta=True, null=True, quality=100, scale=1.0, size=[2000, 1600], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=1.0, size=[2000, 1600], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=1.0, size=[2000, 1600], upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=1.0, size=[2000, 1600], upload_to='project'),
        ),
    ]
